services:

  ms-eventos:
    build: .
    ports:
      - "8083:8083"
    networks:
      - default
      - ticketti-network
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/eventos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

networks:
  ticketti-network:
    external: true
