#Configuración general para el microservicio
spring.application.name=ms-eventos


#Configuración para MySQL
#spring.config.import=optional\:configserver\:http\://localhost\:8083

spring.datasource.url=jdbc:mysql://localhost:3306/ms_eventos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=



#Configuración para JPA/ Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#puerto para localhost
server.port=8083


#Configuración para circuit breaker
#llamadas antes de que empiece a fallar
resilience4j.circuitbreaker.instances.eventoService.minimum-number-of-calls= 3
#(siempre menos que las llamadas minimas) numero de llamadas en estado medio abierto
resilience4j.circuitbreaker.instances.eventoService.permitted-number-of-calls-in-half-open-state= 2 
#cuanto va a a esperar para pasar de abierto a medio abierto
resilience4j.circuitbreaker.instances.eventoService.wait-duration-in-open-state= 5s
#cada cuantas ventanas valida el fallo
resilience4j.circuitbreaker.instances.eventoService.sliding-window-size= 5
#si falla 2 seguidas esto se cae funciona no funciona funciona no funciona al 50% 
#en el 50 o se abre o se mantiene cerrado
resilience4j.circuitbreaker.instances.eventoService.failure-rate-threshold=60
#conexión buena o mala
resilience4j.circuitbreaker.instances.eventoService.register-health-indicator=true 


#Configuración para RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin


#se deshabilita config server
spring.cloud.config.enabled=false
#se deshabilita eureka 
eureka.client.enabled=false
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false


#Configuración para API Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

#frontend -> bff -> api gateway -> microservicio 