spring.application.name=ms-eventos
spring.config.import=optional\:configserver\:http\://localhost\:8888
spring.datasource.url=jdbc:mysql://localhost:3306/ms_eventos
spring.datasource.username=root
spring.datasource.password=
#server.port=8081

#antes de que empiece a fallar
resilience4j.circuitbreaker.instances.eventoService.minimum-number-of-calls= 3

#(siempre menos que las llamadas minimas) numero de llamadas en estado medio abierto
#q es medio abierto?????
resilience4j.circuitbreaker.instances.eventoService.permitted-number-of-calls-in-half-open-state= 2 

#cuanto va a a esperar para pasar de abierto a medio abierto
resilience4j.circuitbreaker.instances.eventoService.wait-duration-in-open-state= 5s

#cada cuantas ventanas valida el fallo
resilience4j.circuitbreaker.instances.eventoService.sliding-window-size= 5

#si falla 2 seguidas esto se cae funciona no funciona funciona no funciona al 50% 
#en el 50 o se abre o se mantiene cerrado
resilience4j.circuitbreaker.instances.eventoService.failure-rate-threshold=60

#registro de salud, si tiene buena conexion o mala conexion el circuit breaker
resilience4j.circuitbreaker.instances.eventoService.register-health-indicator=true